# Generated by Django 6.0.2 on 2026-07-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('marks', models.IntegerField()),
                ('batch', models.CharField()),
                ('branch', models.CharField()),
            ],
        ),
    ]
